### ISSUE TITLE
作者大大，这个程序现在可以安装使用吗？

### ISSUE THREAD

**Issue by shutwin** [makewheels/video-2022#1]
这个程序现在可以安装使用吗？

**Comment by shutwin** [comment]
需要数据库吗？自己导入还是新安装

**Comment by makewheels** [comment]
可以，我现在正在用，你是要用还是怎样。数据库是mongo，不用提前建表

**Comment by shutwin** [comment]
说实话我不会弄，按照网上的教程用idea 打包项目，打包都没弄清楚。。。想请教一下该如何将您的项目打包到网站上呢？

**Comment by shutwin** [comment]
我想做个视频点播的网站，看您的项目不错，我想安装到我自己的服务器上，用的是宝塔面板，后台可以安装tomcat 一键部署。就是不知道如何将您的项目给弄到里面去。。。

**Comment by makewheels** [comment]
这不是一两句能说清的啊，要不加个微信啥的。它还依赖好几个别的项目

**Comment by shutwin** [comment]
我微信号 perftrack 非常感谢
